language: ruby
notifications:
  email:
    on_success: change
    on_failure: always
rvm:
  - 1.8.7
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ruby-head
  - ree
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle --version
before_script:
  - bundle exec rake install
env: TEST_GEM=true
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
