--- 
notifications: 
  email: 
    on_failure: always
    on_success: change
matrix: 
  allow_failures: 
  - rvm: jruby-head
  - rvm: ruby-head
  - rvm: ree
before_script: 
- bundle exec rake install
language: ruby
before_install: 
- gem update --system
- gem --version
- gem install bundler
- bundle --version
env: 
  global: 
  - TEST_GEM=true
  - secure: "D6Sd+bPmNb3P+98W1arc+SbaFV8oC+0NhnZX9fcoIqCHfnVpt6Vd54idUxJv\nhhFUFmySl17zCX/HRaVoscpCYPcJWRWIeXSD4qrHlObaTx+BDKlMAlWl/Y7d\nQy9c4g+QbDhz94l3DeNW7VbCYz/YYyRPBCcZK+K3H1KPmMtngRU="
rvm: 
- 1.8.7
- 1.9.3
- rbx-18mode
- rbx-19mode
- jruby-18mode
- jruby-19mode
- jruby-head
- ruby-head
