language: ruby
notifications:
  email:
    on_success: change
    on_failure: always
rvm:
  - 1.8.7
  - 1.9.3
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle --version
before_script:
  - bundle exec rake install
env:
  - TEST_GEM=true
