---
notifications:
  email:
    on_failure: always
    on_success: change

before_install:
 - gem update --system $RUBYGEMS_VERSION
 - gem --version
 - gem install bundler
 - bundle --version

before_script:
 - bundle exec rake install

language: ruby

env:
  global:
  - TEST_GEM=true
  - RUBYGEMS_VERSION=
  - secure: "D6Sd+bPmNb3P+98W1arc+SbaFV8oC+0NhnZX9fcoIqCHfnVpt6Vd54idUxJv\nhhFUFmySl17zCX/HRaVoscpCYPcJWRWIeXSD4qrHlObaTx+BDKlMAlWl/Y7d\nQy9c4g+QbDhz94l3DeNW7VbCYz/YYyRPBCcZK+K3H1KPmMtngRU="

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2.2.6
  - jruby-19mode
  - rbx-head
  - ruby-head
  - jruby-head
  - ree

matrix:
  exclude:
    - rvm: 1.8.7
      env: RUBYGEMS_VERSION=
    - rvm: jruby-19mode
      env: RUBYGEMS_VERSION=
  include:
    - rvm: 1.8.7
      env:
      - RUBYGEMS_VERSION=1.8.25
      - TEST_GEM=true
      - secure: "D6Sd+bPmNb3P+98W1arc+SbaFV8oC+0NhnZX9fcoIqCHfnVpt6Vd54idUxJv\nhhFUFmySl17zCX/HRaVoscpCYPcJWRWIeXSD4qrHlObaTx+BDKlMAlWl/Y7d\nQy9c4g+QbDhz94l3DeNW7VbCYz/YYyRPBCcZK+K3H1KPmMtngRU="
    - rvm: 1.9.3
      env:
      - RUBYGEMS_VERSION=1.8.25
      - TEST_GEM=true
      - secure: "D6Sd+bPmNb3P+98W1arc+SbaFV8oC+0NhnZX9fcoIqCHfnVpt6Vd54idUxJv\nhhFUFmySl17zCX/HRaVoscpCYPcJWRWIeXSD4qrHlObaTx+BDKlMAlWl/Y7d\nQy9c4g+QbDhz94l3DeNW7VbCYz/YYyRPBCcZK+K3H1KPmMtngRU="
    - rvm: 2.0.0
      env:
      - RUBYGEMS_VERSION=1.8.25
      - TEST_GEM=true
      - secure: "D6Sd+bPmNb3P+98W1arc+SbaFV8oC+0NhnZX9fcoIqCHfnVpt6Vd54idUxJv\nhhFUFmySl17zCX/HRaVoscpCYPcJWRWIeXSD4qrHlObaTx+BDKlMAlWl/Y7d\nQy9c4g+QbDhz94l3DeNW7VbCYz/YYyRPBCcZK+K3H1KPmMtngRU="
    - rvm: jruby-19mode
      env:
      - RUBYGEMS_VERSION=1.8.25
      - TEST_GEM=true
      - secure: "D6Sd+bPmNb3P+98W1arc+SbaFV8oC+0NhnZX9fcoIqCHfnVpt6Vd54idUxJv\nhhFUFmySl17zCX/HRaVoscpCYPcJWRWIeXSD4qrHlObaTx+BDKlMAlWl/Y7d\nQy9c4g+QbDhz94l3DeNW7VbCYz/YYyRPBCcZK+K3H1KPmMtngRU="
    - rvm: rbx-head
      env:
      - RUBYGEMS_VERSION=1.8.25
      - TEST_GEM=true
      - secure: "D6Sd+bPmNb3P+98W1arc+SbaFV8oC+0NhnZX9fcoIqCHfnVpt6Vd54idUxJv\nhhFUFmySl17zCX/HRaVoscpCYPcJWRWIeXSD4qrHlObaTx+BDKlMAlWl/Y7d\nQy9c4g+QbDhz94l3DeNW7VbCYz/YYyRPBCcZK+K3H1KPmMtngRU="
    - rvm: ree
      env:
      - RUBYGEMS_VERSION=1.8.25
      - TEST_GEM=true
      - secure: "D6Sd+bPmNb3P+98W1arc+SbaFV8oC+0NhnZX9fcoIqCHfnVpt6Vd54idUxJv\nhhFUFmySl17zCX/HRaVoscpCYPcJWRWIeXSD4qrHlObaTx+BDKlMAlWl/Y7d\nQy9c4g+QbDhz94l3DeNW7VbCYz/YYyRPBCcZK+K3H1KPmMtngRU="
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head
    - rvm: rbx-2.2.6
      env:
      - RUBYGEMS_VERSION=1.8.25
      - TEST_GEM=true
      - secure: "D6Sd+bPmNb3P+98W1arc+SbaFV8oC+0NhnZX9fcoIqCHfnVpt6Vd54idUxJv\nhhFUFmySl17zCX/HRaVoscpCYPcJWRWIeXSD4qrHlObaTx+BDKlMAlWl/Y7d\nQy9c4g+QbDhz94l3DeNW7VbCYz/YYyRPBCcZK+K3H1KPmMtngRU="

